### PR TITLE
chore: removed unused darwin modules

### PR DESCRIPTION
**Pull request by DavHau**

### CODE REVIEW

**Comment by steveej** [comment]
@DavHau is this already deployed?

**Comment by steveej** [comment]
let me first:

- [ ] double-check the configured github actions to see that they can tolerate a failure of the cachix-action step

**Comment by DavHau** [comment]
It's not yet deployed

**Comment by DavHau** [comment]
... now it is deployed

**Comment by steveej** [comment]
this is causing issues with cachix-action now, because the file that records the store paths at job entry isn't recorded. this leads to all paths in the nix store being pushed to cachix. by design, cachix-action only pushes store paths that were created during the workflow run.

see https://github.com/holochain/holochain/actions/runs/4193073856/jobs/7269507685

**Comment by steveej** [comment]
> [feat: add cachix-watch-store to linux-builder-01](https://github.com/holochain/holochain-infra/pull/20/commits/149944c05bbc54e82b4a7ee5c77b880c8b33bb04)

wohoo, thanks! with that this PR is good to go

**Pull request merged**
